### ISSUE TITLE
Sorting columns has multiple bugs

### ISSUE THREAD

**Issue by zhirzh** [rishabhbits038/react-tabelify#1]
In the demo, sorting by `CGPA` and `Name` has no effect. 

Also, sorting with `University`, `Discipline` and `Year` produces random table. The random order is also not limited to the displayed data, but spans over entire database

**Comment by rishabhbits038** [comment]
Thanks for pointing out.
Will get this fixed.

**Comment by rishabhbits038** [comment]
The issue has been fixed.

**Comment by rishabhbits038** [comment]
The issue has been fixed.
