### ISSUE TITLE
Cannot load bundle.js

### ISSUE THREAD

**Issue by zhirzh** [rishabhbits038/react-tabelify#2]
I cannot get it to server bundle.js
I followed the steps in [`README.md`](https://github.com/rishabhbits038/react-tabelify#steps), but when I open localhost:3000, I get 404 on `http://localhost:3000/javascripts/bundle.js`

**Comment by rishabhbits038** [comment]
A minor change
webpack --progress --colors should be before npm start.

webpack creates the bundled file
